# Generated by Django 4.2.4 on 2023-08-21 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('balance', models.DecimalField(decimal_places=2, max_digits=9)),
                ('wallet_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('date_time', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('ref_num', models.UUIDField(default=uuid.UUID('a2190b9e-07a9-4b81-9a3d-de5c62dd0081'), editable=False, primary_key=True, serialize=False)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WalletApp.wallet')),
            ],
        ),
    ]
