# Generated by Django 4.2.4 on 2023-08-21 21:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('WalletApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='time_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ref_num',
            field=models.UUIDField(default=uuid.UUID('880b7971-08b3-415c-99b2-03c9d467349c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WalletApp.wallet'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
