# Generated by Django 4.2.4 on 2023-08-21 22:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('WalletApp', '0002_wallet_time_created_alter_transaction_ref_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='ref_num',
            field=models.UUIDField(default=uuid.UUID('cafdf667-4a80-4a0c-aa3b-6f7c1457ea41'), editable=False, primary_key=True, serialize=False),
        ),
    ]
